@startuml

title __SQELEVATOR's Class Diagram__\n

  namespace sqelevator {
    class sqelevator.Elevator {
        + acceleration : SimpleIntegerProperty
        + buttonDown : SimpleObjectProperty<boolean[]>
        + buttonReq : SimpleObjectProperty<boolean[]>
        + buttonUp : SimpleObjectProperty<boolean[]>
        + committedDirection : SimpleObjectProperty<Direction>
        + currentCapacity : SimpleIntegerProperty
        + currentFloor : SimpleIntegerProperty
        + currentSpeed : SimpleIntegerProperty
        + currentWeight : SimpleIntegerProperty
        + door : SimpleObjectProperty<DoorStatus>
        + elevatorId : long
        + elevatorNumber : int
        + feetFromBase : SimpleIntegerProperty
        + lastUpdate : SimpleIntegerProperty
        + serviceableFloors : SimpleObjectProperty<Set<Integer>>
        + targetFloor : SimpleIntegerProperty
        {static} - elevatorIdCounter : long
        + Elevator()
        + toString()
    }
  }
  

  namespace sqelevator {
    interface sqelevator.IElevator {
        {static} + ELEVATOR_DIRECTION_DOWN : int
        {static} + ELEVATOR_DIRECTION_UNCOMMITTED : int
        {static} + ELEVATOR_DIRECTION_UP : int
        {static} + ELEVATOR_DOORS_CLOSED : int
        {static} + ELEVATOR_DOORS_CLOSING : int
        {static} + ELEVATOR_DOORS_OPEN : int
        {static} + ELEVATOR_DOORS_OPENING : int
        {abstract} + getClockTick()
        {abstract} + getCommittedDirection()
        {abstract} + getElevatorAccel()
        {abstract} + getElevatorButton()
        {abstract} + getElevatorCapacity()
        {abstract} + getElevatorDoorStatus()
        {abstract} + getElevatorFloor()
        {abstract} + getElevatorNum()
        {abstract} + getElevatorPosition()
        {abstract} + getElevatorSpeed()
        {abstract} + getElevatorWeight()
        {abstract} + getFloorButtonDown()
        {abstract} + getFloorButtonUp()
        {abstract} + getFloorHeight()
        {abstract} + getFloorNum()
        {abstract} + getServicesFloors()
        {abstract} + getTarget()
        {abstract} + setCommittedDirection()
        {abstract} + setServicesFloors()
        {abstract} + setTarget()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
